# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Summary
    url: /#section-my-resume-biography-3
    weight: 10
  - name: About Me
    url: /#about-me
    weight: 11
  - name: Research Highlights
    url: /#research-highlights-title
    weight: 12
  - name: Awards & Observing Programs
    url: /#section-awards-and-observing
    weight: 13
  - name: Publications
    url: /#papers
    weight: 20
  - name: CV
    url: uploads/franson_CV_june26_2024.pdf
    weight: 40
